#variables
@baseUrl = http://127.0.0.1:8000
@productId = 4
### Get All Products

GET {{baseUrl}}/products HTTP/1.1

### Get Product by ID

GET {{baseUrl}}/products/{{productId}}/

### Create a Product

POST {{baseUrl}}/products HTTP/1.1
content-type: application/json

{
    "name": "Another Five",
    "description": "Some description",
    "price" : "7.99"
}


### Update Product
PUT {{baseUrl}}/products/{{productId}}/
Content-Type: application/json

{
  "name": "Updated Product Name",
  "price": 29.99,
  "description": "This product was updated via REST Client."
}

### Delete Product
DELETE {{baseUrl}}/products/{{productId}}/

